# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2544029b2fb87285caacb935b62695f0d548f559be79804740810fe5f73e0caad7307d2991d374f2f5bb71fc40182ccc70cc1159f102d3aa257ad4278cfef004

test:
  secret_key_base: 76f7c6fdc24e3272770233a6eccae4690b82f63c25f9c7f58a5d4ec907bfe8f5dd68455f112e9a07f51afd6710b0a42bec9ea70d15dc8de8d3028818cfad2b11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
